defaults:
  - override /model_cfg@_global_: qwen3_8b
  - override /data_cfg@_global_: teacher_bespoke_stratos
  - override /trainer_cfg@_global_: teacher_gspo
  - _self_

# Use your SFT checkpoint from epoch 5
model_name_or_path: /home/user/trl/RLT/results/pre_rl_model_qwen3_7k/checkpoint-2190

bf16: true

# Training parameters
max_steps: 200
num_train_epochs: 1.0

save_strategy: "steps"
save_steps: 50
do_eval: true
save_final_model: true

eval_strategy: steps
eval_steps: 10

logging_steps: 1
logging_strategy: steps

# Batch size configuration
train_batch_size: 512
per_device_train_batch_size: 1
generation_aggregation_steps: 128

# Generation parameters
num_generations: 32
temperature: 0.7
unbias_log_probabilities: true

# GSPO specific parameters
learning_rate: 0.000001
beta: 0.04

# Reference model sync
sync_ref_model: true
ref_model_mixup_alpha: 0.9
ref_model_sync_steps: 32

# Student model for evaluation
student_model: "bespokelabs/Bespoke-Stratos-32B"
student_model_init_kwargs: null

offload_untrained_models: true

# Context windows
max_prompt_length: 16384
max_completion_length: 16384

# Reward coefficients
answer_log_prob_coeff: [1, 0.01]
kl_penalty_reward_coeff: [3, 0.03]
normalize_log_prob_fn: null
clip_log_prob: 100000
normalize_kl_fn: null
clip_kl: 100000
reduction_log_prob_fn: ["mean", "min"]
reduction_kl_fn: ["mean", "max"]
use_schulman_kl_estimation: false
not_matched_penalty: -1.0
unbias_teacher_log_probs: true
unbias_student_log_probs_temp: 0.7

save_completions_probability: 0.1

lr_scheduler_type: "constant"
lr_scheduler_kwargs: ~

wandb_project: rl4lm_teacher_gspo
wandb_run_name: teacher_gspo_qwen3_epoch5

output_dir: ${results_dir}/gspo_teacher_qwen3

# VLLM settings
vllm_port: 8765
use_vllm: false
use_vllm_server: true
vllm_host: 2dc3509b
num_vllm_clients: 2
